# Use the PHP 7.3 runtime (BETA) by replacing "php72" below with "php73"
runtime: php72

entrypoint: serve gcloud-entry.php

handlers:
- url: /assets
  static_dir: assets
- url: /uploads
  static_dir: uploads
- url: /.*
  script: auto
  secure: always
