runtime: php80
service: default

automatic_scaling:
  max_instances: 1  

entrypoint: serve gcloud-entry.php

handlers:
- url: /assets
  static_dir: assets
- url: /uploads
  static_dir: uploads
- url: .*
  script: auto
  secure: always

runtime_config:
  enable_stackdriver_integration: true
