runtime: php72
service: default

entrypoint: serve gcloud-entry.php

handlers:
- url: /assets
  static_dir: assets
- url: /uploads
  static_dir: uploads
- url: /.*
  script: auto
  secure: always


  