version: '3.1'

services:
  db_mysql:
    image: mysql/mysql-server:latest
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: dropapp_root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: dropapp_dev
    volumes:
      - ./.docker/data/mysql:/var/lib/mysql
    ports:
      - "9906:3306"
  web:
    build: .docker/php 
    depends_on:
      - db_mysql
    volumes:
      - .:/var/www/html/
    ports:
      - "8100:80"
    environment:
      # WARNING: you do *not* want these environment variables set
      # in a production environment, as they enable remote
      # debugging
      GOOGLE_CLOUD_PROJECT: DUMMY_ID 
      XDEBUG_CONFIG: remote_host=host.docker.internal remote_port=9000 remote_enable=1 idekey=IDEA_DEBUG profiler_enable=1 profiler_output_dir=/tmp/xdebug-profiler
    stdin_open: true
    tty: true

