services:
  db_mysql:
    image: mysql/mysql-server:8.0
    command: --default-authentication-plugin=mysql_native_password --lower_case_table_names=1
    environment:
      MYSQL_ROOT_PASSWORD: dropapp_root
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: dropapp_dev
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "9906:3306"
  web:
    build: .docker/php 
    depends_on:
      - db_mysql
    volumes:
      - .:/var/www/html/
      - ./.docker/php/dropapp.conf:/etc/apache2/sites-available/000-default.conf
      - ./.docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./.docker/php/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini
    ports:
      - "8100:80"
    environment:
      # set to empty, so we don't initialize GCP specific config
      # as we have no auth set locally
      GOOGLE_CLOUD_PROJECT: 
    stdin_open: true
    tty: true

