version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.5.0
  cypress: cypress-io/cypress@1.25.0
jobs:
  build:
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
      - image: circleci/node:4.8.2
    working_directory: ~/project
    steps:
      - checkout
      - run: sudo docker-php-ext-install pdo_mysql exif
      # load composer cache
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.lock" }}
      - run: composer install -n
      # run linting (before we generate templates)
      - run: vendor/bin/parallel-lint --exclude vendor .
      # these rules match the ones enabled by default by the "fterrag.vscode-php-cs-fixer" vs code extension
      - run: php vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix . --dry-run --verbose --rules @PhpCsFixer
      # build static assets including templates
      - run: php build.php
      # install again, but with no dev dependencies this time (for deploy)
      - run: composer install -n --optimize-autoloader --no-dev
      # save composer cache
      - save_cache:
          key: composer-v1-{{ checksum "composer.lock" }}
          paths:
            - vendor
      # save output
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

  deploy:
    parameters:
      serviceName:
        type: string
      envVariablePrefix:
        type: string
    docker:
      - image: circleci/php:7.3-stretch-node-browsers
    steps:
      - attach_workspace:
          at: workspace
      - gcp-cli/install
      - run: sudo docker-php-ext-install pdo_mysql
      - run: |
          cd workspace
          # record version
          echo "CircleCI build number:${CIRCLE_BUILD_NUM}
            Git hash: ${CIRCLE_SHA1}
            ${CIRCLE_TAG+Release: ${CIRCLE_TAG}}" > assets/version.txt
          # generate config file
          echo "<?php
            \$settings['version'] = '${CIRCLE_BUILD_NUM}';
            ${CIRCLE_TAG+\$settings['release'] = '${CIRCLE_TAG}';}
            \$settings['db_socket'] = '/cloudsql/${BOXWISE_PRIMARYDB_SOCKET}';
            \$settings['db_database'] = '${<< parameters.envVariablePrefix >>DBNAME}';
            \$settings['db_user'] = '${<< parameters.envVariablePrefix >>DBNAME}';
            \$settings['db_pass'] = '${<< parameters.envVariablePrefix >>DBPASS}';
            \$settings['sendgrid_key'] = '${BOXWISE_SENDGRID}';
            \$settings['sentry_key'] = '${BOXWISE_SENTRY}';" > library/config.php
          echo "paths:
            migrations: '%%PHINX_CONFIG_DIR%%/db/migrations'
            seeds: '%%PHINX_CONFIG_DIR%%/db/seeds'
          environments:
            default_migration_table: phinxlog
            << parameters.serviceName >>:
                adapter: mysql
                host: 127.0.0.1
                name: ${<< parameters.envVariablePrefix >>DBNAME}
                user: root
                pass: ${BOXWISE_PRIMARYDB_ROOTPASS}
                port: 3306
                charset: utf8
                mysql_attr_init_command: SET SQL_MODE = 'NO_AUTO_VALUE_ON_ZERO'
          version_order: creation" > phinx.yml
          # generate google app engine config for target environment
          sed 's/service: default/service: << parameters.serviceName >>/g' app.yaml > app-<< parameters.serviceName >>.yaml
          if [ << parameters.serviceName >> == production ]; then echo -e "\ninstance_class: F2" >> app-production.yaml; fi;
      - run: |
          # get google credentials
          echo $GOOGLE_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          # download cloud sql proxy to enable db access
          curl -o cloud_sql_proxy https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64
          chmod +x cloud_sql_proxy
      - run:
          command: ./cloud_sql_proxy -instances=${BOXWISE_PRIMARYDB_SOCKET}=tcp:3306
          background: true
      - run: |
          # wait for cloud sql proxy to initialize
          sleep 1s
          cd workspace
          # apply db changes 
          echo "Migrating << parameters.serviceName >> database"
          vendor/bin/phinx migrate -e << parameters.serviceName >>
          # deploy
          gcloud app deploy app-<< parameters.serviceName >>.yaml --version ${CIRCLE_BUILD_NUM}
          gcloud app deploy cron.yaml dispatch.yaml --version ${CIRCLE_BUILD_NUM}
  
  create-sentry-release:
    docker: 
      - image: circleci/node:4.8.2
    steps:
      - checkout
      - run:
          name: Create Sentry Release
          command: |
            curl -sL https://sentry.io/get-cli/ | bash
            export SENTRY_RELEASE=$CIRCLE_TAG
            sentry-cli releases new -p $SENTRY_PROJECT $SENTRY_RELEASE
            sentry-cli releases set-commits --auto $SENTRY_RELEASE
            sentry-cli releases finalize $SENTRY_RELEASE

workflows:
  build-and-deploy:
    jobs:
    - build
    # baseUrl for cypress is set in cypress.json (currently staging.boxwise.co)
    - cypress/run:
        yarn: true
        record: true
        wait-on: 'https://staging.boxwise.co/'
        no-workspace: true
        requires:
          - deploy-staging
        filters:
          branches:
            only: master
        post-steps:
          - store_test_results:
              path: cypress/results
    - deploy:
        name: deploy-staging
        envVariablePrefix: BOXWISE_STAGING_
        serviceName: default
        requires:
          - build
        filters:
          branches:
            only: master
    - build:
        name: build-production
        filters:
          tags:
            only: /^v.*/
    - deploy:
        name: deploy-demo
        envVariablePrefix: BOXWISE_DEMO_
        serviceName: demo
        requires:
          - build
        filters:
          branches:
            only: production
          tags:
            only: /^v.*/
    - deploy:
        name: deploy-prod
        envVariablePrefix: BOXWISE_PROD_
        serviceName: production
        requires:
          - build
        filters:
          branches:
            only: production
          tags:
            only: /^v.*/
    - create-sentry-release:
        name: create-sentry-release-for-production
        # requires:
        #   - deploy-prod
        filters:
          branches:
            only: fix_sentry_releases_versioning
          tags:
            only: /^v.*/
