<?php /* Smarty version Smarty-3.1.18, created on 2015-06-02 18:35:50
         compiled from "2147a721d9dba54d0f3aae0f68d2802eb57f55d6" */ ?>
<?php /*%%SmartyHeaderCode:1818241460556ddb668f9086-49948130%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '2147a721d9dba54d0f3aae0f68d2802eb57f55d6' => 
    array (
      0 => '2147a721d9dba54d0f3aae0f68d2802eb57f55d6',
      1 => 0,
      2 => 'string',
    ),
  ),
  'nocache_hash' => '1818241460556ddb668f9086-49948130',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.18',
  'unifunc' => 'content_556ddb66921dd8_19298569',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_556ddb66921dd8_19298569')) {function content_556ddb66921dd8_19298569($_smarty_tpl) {?><blockquote>
<p>Overdracht van kennis is de meest spectaculaire belevenis die ik ken. Je ontmoet en je vindt. Of niet. Allebei onwaarschijnlijk prachtig. Ik schuur graag tegen je aan op &#8217;t scherpst van de snede waar radicaliteit zichzelf ontmoet.</p>
</blockquote>
<p>De laatste tien jaar is het werk van Adelheid Roosen volledig verweven met de zoektocht naar de Ander. Dat wordt zichtbaar in haar ontmoetingen met migranten, in haar succesvolle theaterstukken en ook in de documentaire Mam (2009) waarin zij het wonderlijke proces beziet van haar moeder nu zij Alzheimer heeft. Het is geen&#160; poging het vreemde te begrijpen. Roosen kantelt het perspectief en probeert daarmee te tonen dat er feitelijk geen vreemde is. &#160;</p>
<p>Haar reputatie als maker en actrice vestigt ze in 1988 met 'Tergend Langzaam Wakker Worden', gebaseerd op het stuk van Clara S. van Elfriede Jelinek, waarvoor ze de Prosceniumprijs kreeg voor de beste voorstelling. Daarna maakt ze solo&#8217;s,&#160; onder andere gebaseerd op het werk van Clarice Lispector en Franz Xaver Kroetz.&#160; Een van deze solo&#8217;s, 'Van Top Tot Teen Te Trillen', gaat over de feminisering van de samenleving. &#160;</p>
<p>Vanaf 2003 schrijft en regisseert Adelheid Roosen drie voorstellingen over moslimmigranten: 'Vijf op je Ogen', 'Gesluierde&#160; Monologen' en 'Is.Man'. De laatste twee, respectievelijk over sensualiteit bij moslimvrouwen en eerwraak, beleven succesrijke tournees door Turkije, Amerika, Belgi&#235; en Frankrijk en waren te zien op festivals in Jordani&#235;, Berlijn en Egypte. 'Gesluierde Monologen' is zelfs opgevoerd voor de Tweede Kamer en in een Moskee, toen het parlementaire debat over de grondrechten van religieuze minderheden in Nederland voor het eerst zijn hoogtepunt bereikte.&#160; &#160;</p>
<p>In 2005 richt zij het Zina op, een collectief van makers dat verhalen verzamelt in de wijken en deze toont in audio- en video-installaties, in tentoonstellingen en voorstellingen. Als actrice vertolkt Adelheid ook rollen bij grote repertoiregezelschappen. Bij Toneelgroep Amsterdam speelde ze bijvoorbeeld Portia in Shakespeare&#8217;s 'De Koopman van Veneti&#235;' en verder was zij de wraakengel in 'Romeo en Julia', beide in de regie van de Syrisch-Nederlandse theatermaker Ola Mafaalani. &#160;</p>
<p>In 2008 cre&#235;ert zij Adelheid|Female Economy, het artistieke bureau waarmee ze haar beweging vol ontmoetingen met de Ander kan voortzetten en verwerken in films,&#160; theatrale concepten, performances en voorstellingen. &#160; Het jaar erop maakt Adelheid de documentaire 'Mam' (2009). Hierin volgt ze als een Alice in Wonderland het wonderlijke en ook intieme traject van haar moeder die Alzheimer had. &#8216;Ik zie haar niet verdwijnen, ik zie haar tevoorschijn komen&#8217;. &#160;</p>
<p>Voor de voorstelling 'Zina neemt de Wijk', 2010, woont Roosen met de makers van Zina drie maanden in drie achterstandswijken in Groningen. Zij gaan in adoptie bij wijkbewoners om het contact met de ander te verdiepen, verzamelen hun verhalen die de pijler worden van deze voorstelling, een co-productie met het Noord Nederlands Toneel, in de regie Ola Mafaalani.</p>
<p>Zo ontstond er de beweging naar de wijk en van de wijk naar het theater. &#160; Een jaar later, in 2011, trekt Roosen met de makers van Zina en de Veenfabriek naar&#160; twee volkstuinen in Amsterdam en Leiden voor de locatieproductie '#MOES'. Een voorstelling waarin acteurs en tuinbewoners, verspreid door de tuinen verhalen vertellen, onkruid laten bloeien, liederen laten klinken en met weemoed relaties laten verwelken omdat niet alles altijd kan blijven bestaan. &#160;</p>
<p>Datzelfde jaar reist Roosen samen met de jonge regisseur Merel de Groot naar Damascus. Met kunstenaars uit Syri&#235; en studenten van de plaatselijke kunst- en theateracademie maken ze een tien dagen durende beweging van ontmoetingen door de stad die uitmondt in de installatie 'to the You I call the Other'. De echo van deze voorstelling was in juni 2012 in het Academisch Medisch Centrum in Amsterdam te zien en in 2013 in het Wilhelmina Kinderziekenhuis in Utrecht. &#160;</p>
<p>In het najaar van 2011 gaat in het Petit Th&#233;&#226;tre in Parijs 'Les Monologues Voil&#233;s', de&#160; Franse versie van 'Gesluierde Monologen', in premi&#232;re in regie van Roosen. De voorstelling speelt hier tot 1 januari 2012 en gaat in najaar 2012 en voorjaar 2013 op&#160; tournee door heel Frankrijk, Canada en Zwitserland. In november van hetzelfde jaar ontwikkelt Roosen samen met Zina de eerste editie van de 'WijkSafari', in de wijk Slotermeer in Amsterdam. Publiek wordt gedurende een middag geadopteerd door twee wijkbewoners, die&#160; hen zo onderdeel maken van&#160; hun dagelijkse routine. Het begin van een reis door een hyperrealiteit waarin intense ontmoetingen mogelijk worden gemaakt. Waarin realiteit overgaat in theatrale&#160; beelden. &#160;</p>
<p>In mei 2012 kent de 'WijkSafari' Slotermeer een succesvolle uitgebreide&#160; editie, waarvan in voorjaar 2013 een vervolg speciaal voor Utrecht wordt gemaakt. &#160;</p>
<p>'Geweld Verhalen Karavaan' (2012) is een audio-video installatie waarin verzamelde&#160; interviews zijn verwerkt tot monologen die door de ge&#239;nterviewden zelf zijn ingesproken. Samen met de ge&#239;nterviewden wordt geprobeerd een antwoord te vinden op vragen hoe geweld ontstaat, hoe problemen escaleren, hoe je eruit kunt&#160; komen en wat de rol van familie en buren is. &#160;</p>
<p>De eerder genoemde documentaire 'Mam' werd genomineerd voor de IDFA Award for Short Documentary. Voor de film Broos (1997)&#160; van regisseur Mijke de Jong krijgt&#160; zij, evenals de vier actrices met wie zij het script van de film maakte, een Gouden Kalf. In 2011 beginnen de opnamen voor het vervolg 'Brozer', welke in 2014 uitkomt op het Internationaal Filmfestival van Toronto. In 2009 krijgt ze de Amsterdam Prijs voor haar grensoverschrijdende bijdrage aan de kunsten in Amsterdam en in september 2012 ontvangt Adelheid de Prosceniumprijs voor het gehele oeuvre dat zij ontwikkelde met haar stichtingen Female Economy en Zina. &#160;</p>
<p>Als voorzitter van de jury van het Nederlands Theater Festival 2009/2010 initieert zij de WijkJury. Een theaterjury van veertien vrouwen met verschillende culturele achtergrond, wonend in diverse Amsterdamse wijken, die een eigen selectie maakt voor het Nederlands Theater Festival. Ondertussen is editie 6 van de WijkJury in volle gang en zijn er WijkJury&#8217;s opgestart in Utrecht, Zwolle, Dordrecht en Arnhem. &#160;</p>
<p>In 2014 gaat Adelheid met haar 'WijkSafari' de grenzen over naar Mexico Stad en cre&#235;ert daar een onvergetelijke scootertocht door de ruige straten van de wijk Tepito met een overweldigende Mexicaanse media-aandacht. Met haar laatste project, 'de Oversteek', trekt zij met een honderdtal wijkbewoners naar podia van schouwburgen door het hele land. Als een nieuw hedendaags volk wandelden zij het toneelstuk 'Dantons Dood' van Johan Simons over de Franse Revolutie binnen en brachten vervolgens de nacht op het podium door.</p>
<p>Als afsluiter van het seizoen bracht Adelheid haar adoptiemethodiek in praktijk met studenten van de faculteit theater van het Bard College in New York, die geadopteerd werden door vrijwilligersorganisatie AmeriCorps. Dit seizoen krijgt de samenwerking met Ola Mafaalani|Noord Nederlands Toneel, die met 'Zina neemt de Wijk' is ingezet, een vervolg in de social sculpture 'Iets Zachts' gekoppeld aan de NNT voorstelling 'De laatkomer'. 'Hetty &amp; George' beleeft zijn derde reprise en daarnaast staat 'Laag Water' op stapel, een partituur van Wim T. Schippers in coproductie met de Veenfabriek. &#160;</p>
<p>Naast veel theater- en televisiewerk doceert Adelheid Roosen sinds 1986 aan de Amsterdamse Toneelschool en Kleinkunst Academie. Ook was zij mentor bij DasArts. In 2010 en 2011 was Roosen ambassadeur huiselijk geweld. &#160; Adelheid Roosen: &#8216;De overdracht van kennis is de meest spectaculaire belevenis die ik ken. Eigenlijk is het een wonder. Je ontmoet en je vindt. Of niet. Allebei, onwaarschijnlijk prachtig. Ik schuur graag tegen je aan op &#8217;t scherpst van de snede waar radicaliteit zichzelf ontmoet. Ik kom bij je thuis uit nieuwsgierigheid. Binnen de podiumkunst heb ik geen voorkeur voor een discipline.&#8217; &#160; &#160;</p><?php }} ?>
