<?php /* Smarty version Smarty-3.1.18, created on 2016-10-13 14:47:05
         compiled from "8756526d78a4317650bf9f8cd25ade24aa07c99c" */ ?>
<?php /*%%SmartyHeaderCode:86730257657ff82495dc5e5-24484221%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    '8756526d78a4317650bf9f8cd25ade24aa07c99c' => 
    array (
      0 => '8756526d78a4317650bf9f8cd25ade24aa07c99c',
      1 => 0,
      2 => 'string',
    ),
  ),
  'nocache_hash' => '86730257657ff82495dc5e5-24484221',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.18',
  'unifunc' => 'content_57ff824961b554_75134726',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_57ff824961b554_75134726')) {function content_57ff824961b554_75134726($_smarty_tpl) {?><p>We kijken terug op een zeer inspirerende bijeenkomst. We waren vereerd met het bezoek van minister Jet Bussemaker van OCW. Zij toonde zich "zeer enthousiast over de resultaten" en gaf te kennen dat Cultuur+Ondernemen door mag gaan met deze leenfaciliteit. De Talentlening voor cultuur stelt kunstenaars en culturele instellingen in staat om te investeren in zichzelf, met fantastische resultaten.&#160;</p>
<p>Bekijk hieronder het fotoverslag van 10 oktober 2016.</p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/3.-b5MVH1290.jpg" alt="" />Minister Jet Bussemaker begroet Steven de Waal (voorzitter raad van toezicht van Cultuur+Ondernemen): &#8220;Vandaag gaan wij niet alleen de voorbeelden zien, maar ook de onderliggende trends analyseren, zodat er een goed beeld ontstaat van de betekenis van leningen voor de kunst- en cultuursector&#8221;, aldus De Waal.<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/1.-b5MVH1181-kopie.jpg" alt="" />Op de financieringspresentatie &#8220;De kunst van het lenen&#8221; kwamen veel bezoekers af. Dat reflecteert de belangstelling voor het nieuwe financieringsinstrument.<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/13.-b5MVH2054.jpg" alt="" /><br />Minister Bussemaker (Onderwijs, Cultuur en Wetenschap) toont zich enthousiast over de resultaten van &#233;&#233;n jaar Talentlening: &#8220;Ik ben verrast door de reikwijdte en heb hoge verwachtingen van het vervolg.&#8221; De minister kreeg het rapport uit handen van Jo Houben (directeur-bestuurder Cultuur+Ondernemen).<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/14.-b5MVH2091-kopie.jpg" alt="" />&#8220;De Talentlening komt niet <em>in de plaats van</em> subsidies, maar is daar een welkome aanvulling op. Voor de toekomst wil ik graag kijken hoe we die mix verder kunnen brengen. Deze evaluatie geeft daar interessante input voor&#8221;, aldus minister Bussemaker.<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/8.-b5MVH1634-kopie.jpg" alt="" />Jo Houben (directeur-bestuurder Cultuur+Ondernemen): "De Talentlening voor cultuur stelt kunstenaars en culturele instellingen in staat om te investeren in zichzelf, met fantastische resultaten. En de aflossingen komen weer terug in het fonds zodat ook anderen er gebruik van kunnen maken. Dat geeft een enorme spin off."<br /><br /></p>
<p><img src="/content/original/1010Financieringpresentatie/6.-b5MVH1572-kopie.jpg" alt="" /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/4.-b5MVH1470-kopie.jpg" alt="" />Steven de Waal (voorzitter raad van toezicht Cultuur+Ondernemen) en minister Jet Bussemaker (Onderwijs, Cultuur en Wetenschap).<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/9.-b5MVH1832-kopie.jpg" alt="" />&#8220;Eigenlijk bouwen we aan een Financieel Ecosysteem Cultuur: de plek waar initiatiefnemers, investeerders en financiers elkaar en ontmoeten en elkaar leren verstaan&#8221;, zo betoogt Roelof Balk (directeur <a href="http://www.fondscultuurfinanciering.nl/" target="_blank">Fonds Cultuur+Financiering</a>) bij de presentatie van het Evaluatierapport.<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/10.-b5MVH1936-kopie.jpg" alt="" />Co-referent Lex van Teeffelen (<a href="https://www.hu.nl/" target="_blank">Hogeschool Utrecht</a>): &#8216;Het effect van de cultuurleningen is veel groter dan alleen financieel. Het levert de kunstenaars ook meer opdrachten op, een groter netwerk, en een verbetering van de inkomenpositie. Bovendien investeren zij ook eerder in kennis en vaardigheden.&#8221; &#160;<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/16.-b5MVH2170-kopie.jpg" alt="" />&#8220;Als je succes hebt, moet je snel kunnen opschalen. Dan moet je ook middelen hebben om te kunnen investeren. De Talentlening gaf mij die mogelijkheid, waardoor ik nieuwe en grote opdrachten aankon, ook vanuit het buitenland. Dat geeft je ontwikkeling echt een boost&#8221;, legt leningnemer Lucas van Woerkum uit. &#160;<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/20.-b5MVH2366-kopie.jpg" alt="" />In het panelgesprek kwam goed naar voren op welke punten kunst en cultuur zich financieel gezien onderscheidt van &#8216;gewone&#8217; bedrijfstakken, maar toch ook waar de overeenkomsten liggen. &#8220;Ook in het zakelijke midden- en kleinbedrijf hebben ondernemers vaak weinig kaas gegeten van financiering. Het is dus heel normaal dat je daar aandacht aan moet besteden.&#8221;<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/17.-b5MVH2194-kopie.jpg" alt="" />Leningnemer Frank Groot van <a href="https://kinorotterdam.nl/" target="_blank">KINO Rotterdam</a>: &#8220;Voor ons was de Talentlening de <em>missing link</em> in de financieringspuzzel. Het hielp ook bij het verkrijgen van de bancaire financiering.&#8221; &#160;<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/18.-b5MVH2234-kopie.jpg" alt="" />&#8220;Voor ons is het onderdeel training en begeleiding zeker zo belangrijk. Kunstenaars en culturele organisaties moeten iets te kiezen hebben. Daarom doen wij als&#160;<a href="https://www.amsterdamsfondsvoordekunst.nl/" target="_blank">Amsterdams Fonds voor de Kunst</a> met de Amsterdamse Cultuurlening mee aan deze ontwikkelingen,&#8221; aldus Clayde Menso, directeur AFK.<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/19.-b5MVH2276-kopie.jpg" alt="" />Caroline Oosterbaan, bankier bij&#160;<a href="https://www.nibc.nl/" target="_blank">NIBC</a> en Raad van Toezicht <a href="http://www.fondscultuurfinanciering.nl/" target="_blank">Fonds Cultuur+Financiering</a>: &#8220;Financiering en kredietverlening gaan altijd om het afwegen van risico&#8217;s. Je moet je goed verdiepen in de casus en verstand hebben van de sector. Bij dit soort kleinschalige leningen met lage rendementen wordt dat voor een gewone bank veel te kostbaar. Zeker omdat de kunstensector zich zakelijk gezien moeilijk laat beoordelen.&#8221;<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/21.-b5MVH2507-kopie.jpg" alt="" />Lucas Hendricks, Raad van Toezicht <a href="http://www.fondscultuurfinanciering.nl/" target="_blank">Fonds Cultuur+Financiering</a>: &#8220;Het gaat ook om het leggen van de verbinding naar andere financiers. Met een cultuurlening kan je de brug slaan naar nieuwe geldbronnen die vaak voor starters nog onbereikbaar zijn.&#8221; &#160;<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/5.-b5MVH1506-kopie.jpg" alt="" />Soulzanger&#160;<a href="http://www.steffenmorrison.com/" target="_blank">Steffen Morrison</a> en zijn band laten zien en horen waarom investeren in kunst en cultuur loont. &#160;<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/7.-b5MVH1613-kopie.jpg" alt="" />&#8220;Als kunstenaar moet je investeren in je presentatiemateriaal. Ik heb een CD gemaakt en heb daar elke dag plezier van. Met de opbrengsten van mijn optredens betaal ik de schuld af, zodat ik straks weer Cultuurlening-vrij ben&#8221;, aldus leningnemers <a href="http://www.steffenmorrison.com/" target="_blank">Steffen Morrison</a>.<br /><br /></p>
<p class="caption"><img src="/content/original/1010Financieringpresentatie/12.-b5MVH2018-kopie.jpg" alt="" /><a href="http://www.kuitenbrouwer.nl/" target="_blank">Carel Kuitenbrouwer</a>&#160;gaf een perfomance.</p><?php }} ?>
