<?php /* Smarty version Smarty-3.1.18, created on 2015-10-27 08:56:43
         compiled from "b8644f6ed66e9355cd8c62e37b9dcc5c0cc8e233" */ ?>
<?php /*%%SmartyHeaderCode:59919034562f2e3b8fb238-28436823%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    'b8644f6ed66e9355cd8c62e37b9dcc5c0cc8e233' => 
    array (
      0 => 'b8644f6ed66e9355cd8c62e37b9dcc5c0cc8e233',
      1 => 0,
      2 => 'string',
    ),
  ),
  'nocache_hash' => '59919034562f2e3b8fb238-28436823',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.18',
  'unifunc' => 'content_562f2e3b934a89_69835983',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_562f2e3b934a89_69835983')) {function content_562f2e3b934a89_69835983($_smarty_tpl) {?><p>Belangrijk uitgangspunt van de opleiding is een goede match tussen artistieke verbeeldingskracht, maatschappelijk engagement en cultureel ondernemerschap.&#160;Studieleider is de Brabantse gerenommeerde acteur en voormalig eigenaar van Het Bossche Makershuis <a href="http://www.linkedin.com/in/romijnconen" target="_blank">Romijn Conen</a>. De opleiding is een initiatief van Cultuur+Ondernemen en Cal-XL. <br /><br />De deelnemers werkten gaandeweg de opleiding aan hun eigen &#8216;sociaalartistieke signatuur' en aan een beroepspraktijk die aansluit op urgente maatschappelijke vraagstukken waar daadwerkelijk ook een &#8216;markt' voor is. <br /><br />Twee KiS-studenten, Anneke Wijn en Juul Langenberg, hebben in juli 2015 hun opleiding afgerond met een eindpresentatie en kijken terug op afgelopen jaar. <br /><br /><strong> <em>Anneke Wijn </em></strong><em>heeft ruime ervaring opgedaan in de onderwijswereld en heeft zich gespecialiseerd in kindgerichte projecten conform de Italiaanse</em><em>&#160;</em><em>Reggio Emilia</em><em>&#160;</em><em>pedagogiek en meervoudige intelligentie. Haar bedrijf CC bureau voor beeldende educatie ontwikkelt en begeleidt educatieve trajecten rondom duurzaamheid, natuur en milieu, kunst en community art. </em><em>In 2011 heeft Anneke (samen met Monique Eilertsen en Maaike Uitenbroek) Het Recycle Huis opgericht, waar wordt gewerkt met duurzame materialen. Meer weten over Anneke? Kijk op haar <a href="http://www.cc-educatie.nl" target="_blank">website</a>.&#160;</em></p>
<p><em><strong>Juul Langenberg</strong> </em><em>heeft beeldende kunst (HKU) en ruimtelijk ontwerp (Academie St. Joost) gestudeerd. Haar werk ontstaat naar aanleiding van ervaringen, fascinaties en verwondering. Het verhaal is het uitgangspunt en het resultaat een mix van beeldende en toegepaste kunst. Juul werkt graag met mensen en houdt zich vooral bezig met het vormgeven van ontmoetingsplekken, decors voor theaterproducties en het ontwerpen van producten voor binnenruimtes en voor buiten. Daarbij ziet zij het samenwerken met andere disciplines en kunstenaars als een ware verrijking. Meer weten over Juul? Kijk op haar <a href="http://www.ver-bind-en.nl" target="_blank">website</a>. </em></p>
<h4><strong>De waarde van kunst </strong></h4>
<p>Voor Anneke is de kunstenaar de lijn, de verbindende factor: &#8220;De kunstenaar ziet het als zijn of haar uitdaging om problemen in een ander daglicht te presenteren en grijpt de kansen om verbindingen in de maatschappij te cre&#235;ren. De kunstenaar leert de niet-kunstenaar bewust anders naar de wereld te kijken.&#8221; Juul wil mensen door middel van kunst op een andere manier naar de wereld om zich heen laten kijken. &#8220;Dat hoeven soms maar hele kleine inzichten te zijn, of hele kleine veranderingen. Maar die kunnen grote resultaten hebben. De uitdaging is om de juiste trigger te vinden. Je moet contact met mensen maken, anders lopen ze je voorbij. Hoe? Dat ontstaat op het moment, op de plek zelf. Je pakt iets op wat aan de hand is: ontevredenheid, verveling, overlast. Daar speel je op in en je gaat grenzen oprekken. Dat is voor mij de waarde van kunst.&#8221; &#160;</p>
<h4><strong>De waarde van KiS </strong></h4>
<p>&#8220;De opleiding is de verdieping in wat ik echt leuk vind&#8221;, aldus Juul. &#8220;KiS gaat over het verkrijgen van een aantal essenti&#235;le handvatten: hoe maak ik een begroting of een projectplan, waar vind ik al die fondsen, welke subsidies vraag ik aan, hoe kom ik verder nog aan geld? Heel praktische zaken waar ik nog niet zo bekend mee was.&#8221; De KiS-opleiding heeft Annekes blik op het culturele veld verbreed. &#8220;Ik heb meer strategisch inzicht verkregen waarmee ik beter kan inspelen op het grotere geheel.&#8221; De gastdocenten vond zij inspirerend. &#8220;Door de verschillende colleges word je je steeds meer bewust van je eigen handelen. Je leert goed nadenken eer je ergens aan begint. Niet alleen de agenda vullen, maar hoe breng ik mezelf en mijn onderneming verder? Ik wil niet iedere keer mezelf herhalen. Ik wil telkens weer een nieuwe uitdaging. Telkens een stukje verder groeien. Door de gastcolleges ben ik veel bewuster gaan werken.&#8221;</p>
<h4><strong>De waarde van delen </strong></h4>
<p>Juul: &#8220;De opleiding vormde een stimulans om de dingen &#8216;dan maar gewoon&#8217; te gaan doen. Dat was wel de grootste aha. Gewoon aanpakken. Niet lullen maar poetsen, zeggen wij. Ik werk graag samen met mensen, maar hoe vind en bereik je een groep? Hoe moet je dat nou allemaal doen? Maar door de vreselijke tijdsdruk had je geen tijd om stil te staan of om het alleen te doen. Wanneer je je plannen deelt met anderen dan opent dat ook weer deuren. Voor je het weet sta je er.&#8221; Wat Anneke heel graag wil is het doorgeven van haar werkwijze aan talentvolle collega&#8217;s die net beginnen. &#8220;Samen kunnen we dan projecten op structurele wijze in een breder draagvlak uitzetten. Tevens wil ik me meer richten op co&#246;rdineren, coachen en begeleiden. Over vijf tot tien jaar hoop ik dat er een goede sturende basis staat waarbij de kind-/mensgerichte aanpak de rode draad is.&#8221;</p>
<h4><strong>De waarde van creatief ondernemerschap </strong></h4>
<p>Als ze terugkijkt op afgelopen jaar, dan heeft Anneke van de module over creatief ondernemerschap het meest geleerd. &#8220;Als zelfstandig ondernemer ben je met je <em>core business</em> bezig, maar daarboven gebeurt ook nog van alles. Op dit moment verandert de maatschappij zo snel; er zijn zoveel initiatieven die bij elkaar komen en samenwerkingsverbanden die worden opgezet. Het is soms moeilijk om dat allemaal te blijven volgen.&#8221; <strong>&#8220;</strong>Praktisch gezien vond ik de module ondernemerschap ook het meest waardevol&#8221;, zegt Juul. &#8220;Dat is een gebied waarin ik nog veel kan groeien. Ondernemen vergt dat je gaat nadenken over de toekomst. Iets wat je liever niet doet, want dat kost veel tijd en je komt er toch niet uit. In de module ondernemerschap werk je aan de ontwikkeling van praktische tools: schrijven van een projectplan, opstellen van budgettering, sparren tijdens intervisie-sessies, aanvragen van subsidies. Om zelfstandig te kunnen opereren en subsidies aan te vragen ben ik een stichting begonnen. Mijn ondernemersvisie ziet er heel anders uit dan toen ik hier startte.&#8221;</p>
<h4><strong>De waarde van een studieleider uit het vak </strong></h4>
<p>Niet alleen in de gezondheidszorg, maar ook vanuit woningbouwcorporaties, gemeenten en het bedrijfsleven stijgt de vraag naar innovatie, vernieuwing en herkadering van de huidige leefbaarheidsvraagstukken. Kunstenaars blijken hierbij van grote waarde te kunnen zijn door hun non-conventionele en positieve aanpak. &#8220;Juist in Brabant bleek er grote behoefte te zijn aan professionele kunstenaars met de juiste competenties om dergelijke projecten te initi&#235;ren of uit te voeren. Reden voor mij om de KiS-opleiding mede te initi&#235;ren&#8221;, aldus Romijn Conen. <br /><br />Als studieleider zag hij de studenten gaandeweg groeien. &#8220;Anneke had al veel ervaring met projecten. Zij ziet door de opleiding in dat ze niet alles alleen kan doen, maar meer moet delegeren. In de toekomst zal zij meer de leiderschapsrol op zich nemen. Juul daarentegen begon aan de opleiding om juist andere mensen te betrekken bij haar idee&#235;n. Zij wilde gaan samenwerken, maar moest hiervoor eerst meer structuur aanbrengen in haar werkwijze. Deze structuur heeft ze gaandeweg de opleiding voor zichzelf ontwikkeld in een helder vijf-punten-plan. Om in het vervolg een nieuw project te starten, moet het minimaal aan deze vijf punten voldoen wil zij het uitvoeren.&#8221; &#160; <br /><br />Zo had de opleiding voor elke student een toegevoegde waarde. Romijn: &#8220;Een ander mooi voorbeeld om te noemen is dat van Dani&#235;lle Coppen. Zij had niet eerder zelfstandig een project geleid, maar pakte het gelijk groots aan&#8221;. In een wijk waar veel negativiteit heerste, wilde zij een community-arts-project opzetten om de leefbaarheid te verbeteren. &#8220;Zij kwam er afgelopen jaar achter dat ze erg goed was in het in beweging krijgen van een groot aantal lokale partijen. Het project werd daardoor veel groter dan gedacht; toch kreeg ze de financiering rond en kon het binnen de geplande tijd worden uitgevoerd. Door omstandigheden kon Dani&#235;lle haar plannen niet zelf uitvoeren en moest ze het overlaten aan anderen. Toen bleek dat zij niet alleen goed is in het opzetten van een groot project, maar ook dat zij haar werkwijze en afspraken zo duidelijk geformuleerd had, dat anderen het z&#243; konden overnemen.&#8221;</p>
<p>De opleiding is een initiatief van Cultuur+Ondernemen en Cal-XL. Het is een gezamenlijke onderneming met DOK-e en Bkkc, in samenwerking met Kunstbalie en Avans Hogeschool. De opleiding wordt gehost door Fontys Hogeschool voor de Kunsten in Tilburg. <br /><br />Wil jij net als Anneke, Juul en Dani&#235;lle leren en experimenteren hoe je kunst en maatschappelijke ontwikkeling met elkaar kunt verbinden? Houd dan onze website in de gaten of neem contact op met <a href="/medewerkers/krista-heijster">Krista</a>.&#160;</p>
<p><em>Foto: Stichting Academie D'imagie<br /><br /></em></p>
<p class="image-left30"><img src="/content/original/Logos/logo-bkkc.jpg" alt="" /></p>
<p class="image-right30"><img src="/content/original/Logos/image-gallery.png" alt="" /></p>
<p class="image-left30"><img src="/content/original/Logos/fontys.png" alt="" /></p>
<p class="image-right30"><img src="/content/original/Logos/kunstbalie.png" alt="" /></p>
<p class="image-right30"><img src="/content/original/Logos/avans-hogeschool.jpg" alt="" /></p>
<p class="image-left30"><img src="/content/original/Logos/logo-doke.png" alt="" />&#160;</p><?php }} ?>
