<?php /* Smarty version Smarty-3.1.18, created on 2015-10-28 10:27:53
         compiled from "d0a0d48b590131a57da7438d42d0df0fa99aa6f2" */ ?>
<?php /*%%SmartyHeaderCode:133852767356309519120d38-51250269%%*/if(!defined('SMARTY_DIR')) exit('no direct access allowed');
$_valid = $_smarty_tpl->decodeProperties(array (
  'file_dependency' => 
  array (
    'd0a0d48b590131a57da7438d42d0df0fa99aa6f2' => 
    array (
      0 => 'd0a0d48b590131a57da7438d42d0df0fa99aa6f2',
      1 => 0,
      2 => 'string',
    ),
  ),
  'nocache_hash' => '133852767356309519120d38-51250269',
  'function' => 
  array (
  ),
  'has_nocache_code' => false,
  'version' => 'Smarty-3.1.18',
  'unifunc' => 'content_563095191580d8_92176864',
),false); /*/%%SmartyHeaderCode%%*/?>
<?php if ($_valid && !is_callable('content_563095191580d8_92176864')) {function content_563095191580d8_92176864($_smarty_tpl) {?><p>Cultuur in Beeld is gericht op&#160;medewerkers en directies van culturele instellingen, kunstenaars, cultureel ondernemers, onderzoekers,&#160; medewerkers van gemeenten, provincies,&#160;ministeries en cultuurfondsen en alle anderen die actief zijn binnen de culturele en creatieve sector. Het centrale thema is dit jaar &#8216;Ruimte voor Cultuur&#8217;.</p>
<h4><strong>Hele dag (10.00 tot 18.00 uur)<br /></strong><strong>CultSpace Cultuur+Ondernemen</strong></h4>
<p>Cultuur+Ondernemen stimuleert ondernemerschap in de cultuursector. We werken aan een florerende sector die zelfstandig kan functioneren. We brengen partijen bij elkaar, zetten nieuwe vraagstukken op de agenda, delen onze kennis en cre&#235;ren daarbij passende instrumenten. We staan culturele organisaties, kunstenaars en creatieven met raad en daad bij om meer rendement te halen uit hun activiteiten. We begeleiden hen bij professionele ontwikkeling, het innoveren van verdienmodellen en het ontwikkelen van goed bestuur en toezicht.</p>
<p>Heb je een ondernemersvraag? Schrijf je dan nu alvast in voor een gratis adviesgesprek op Cultuur in Beeld. Schrijf je in via de blauwe aanmeldknop. Beschrijf je vraag zo uitgebreid mogelijk, dan koppelen wij je aan de juiste adviseur. Je krijgt uiterlijk vrijdag 4 december te horen hoe laat je bent ingedeeld. Een adviesgesprek duurt ongeveer 30 minuten.</p>
<p>Naast onze &#8217;live&#8217;-expertise bieden we enkele ondersteunende items aan op het gebied van Governance en cultureel ondernemerschap en vertellen we je natuurlijk graag wat we in de praktijk voor je kunnen betekenen.</p>
<h4>Hele dag <strong>(10.00 tot 18.00 uur)<br /></strong>CultSpace Fonds Cultuur+Financiering</h4>
<p>Subsidiestromen nemen af. Er is steeds minder geld voor de culturele en creatieve sector. De cultuurleningen van het&#160;<a href="http://www.fondscultuurfinanciering.nl/" target="_blank">Fonds Cultuur+Financiering</a> (een initiatief van Cultuur+Ondernemen) bieden nieuwe mogelijkheden. Voor investeringen in fysieke ruimtes zoals broedplaatsen, werklocaties, theaters of galeries. Of voor evenementen, festivals,&#160; producties en proof of concepts. Uiteindelijk gaat het om waardecreatie voor publiek en samenleving &#233;n om het verzilveren van die waarde in klinkende munt. In het klein en in het groot, voor de korte en de lange termijn. Kom naar onze CultSpace voor een Meet&amp;Greet of geef je alvast op voor een gratis adviesgesprek (via de blauwe aanmeldknop) en verken de (financi&#235;le) mogelijkheden.</p>
<p><em>Naast de CultSpaces maakt Cultuur+Ondernemen ook deel uit van het sprekersprogramma.&#160;Je hoeft je niet van te voren in te schrijven voor onderstaande sessies. Je stelt op de dag zelf een persoonlijk programma samen. Cultuur in Beeld hanteert het principe 'wie het eerst komt het eerst maalt'.&#160;</em></p>
<h4><strong>11.45 - 12.45 uur: Lokaal 14<br /></strong><strong>Flexibel hrm-beleid in de cultuursector</strong></h4>
<p><strong>Sprekers</strong><br /><a href="/medewerkers/karen-de-meester">Karen de Meester</a>&#160;(Cultuur+Ondernemen), Dorien Versloot (SFPK), Agnes Vugts (LCM/Huis voor de Kunsten Limburg)</p>
<p>De cultuursector is in beweging, en niet alleen op creatief gebied. Door de economische ontwikkelingen krimpt het aantal vaste medewerkers. Van organisaties wordt een steeds grotere flexibiliteit verwacht. De diversiteit aan arbeidsrelaties neemt toe. Hoe gaat uw organisatie daarmee om? Het is tijd voor slimme human resource management (HRM) oplossingen. Hoe versterkt u de competenties van uw medewerkers? Hoe zorgt u voor meer in-, door- en uitstroom? Hoe kunt u flexibiliseren en hoe borgt u dan kennis? Hoe werkt u aan duurzame inzetbaarheid? Het Sectorplan Cultuur doet onderzoek naar organisatie en arbeid. Het biedt een HRM-loket met informatie, tools, trainingen, loopbaantrajecten, leerwerkplekken en nog veel meer. In deze workshop hoort u de eerste uitkomsten van het onderzoek naar de stand van zaken op het gebied van personeelsbeleid in de cultuursector. Ook krijgt u informatie over de HRM-check en &#8211;trainingen. Maar brengt u vooral uw eigen onderwerpen in. Door die met elkaar te bespreken vindt u de eerste oplossingsrichting.<br /><br /></p>
<h4><strong>13.30 - 14.00 uur: Lokaal 2</strong> <br /><strong>Regionaal revolverend financieren</strong></h4>
<p><strong>Spreker<br /></strong><a href="/medewerkers/alexander-ramselaar">Alexander Ramselaar</a>&#160;(Cultuur+Ondernemen)<strong> <br /></strong></p>
<p>Revolverend financieren is een actueel onderwerp. Veel steden en regio&#8217;s zijn bereid een fonds in te richten dat culturele instellingen de mogelijkheid biedt een lening af te sluiten voor een investering, of tijdelijke overbrugging. De Amsterdamse, Brabantse en Utrechtse Cultuurlening zijn recente voorbeelden waar publieke en private partners regionaal de handen ineen hebben geslagen. Leningen tot circa &#8364; 40.000 zijn mogelijk. En met succes. De regionale aanpak waarborgt een toegankelijke aanpak die inspeelt op regionale behoeftes. Een aanvulling op het subsidiebeleid van gemeenten en provincies. Recent onderzoek wijst uit dat dergelijke microkredieten ondernemers in de culturele en creatieve sector goed op weg helpen. Het zorgt voor nieuwe opdrachten, vergroot hun professionele netwerk en verbetert hun inkomenspositie. In deze CultTalk gaan we onder andere in op de volgende vragen: wat zijn de ervaringen, resultaten en effecten van regionale revolverende fondsen? Hoe wordt een regionale samenwerking gestructureerd? En wat zijn succesfactoren en randvoorwaarden om een fonds te cre&#235;ren?<br /><br /></p>
<h4><strong>15.15 - 16.15 uur: Lokaal 10</strong> <br /><strong>Verbind toezicht aan de toekomst</strong></h4>
<p><strong> Sprekers</strong><br /><a href="/medewerkers/marceline-loudon">Marceline Loudon</a>&#160;(Cultuur+Ondernemen), Sandra Boer (NVTC), Karin Van der Star (NVTC), Aalt Klaassen (Aalt Klaassen BV)</p>
<p>In deze tijd van vernieuwing en professionalisering binnen de cultuursector, is het noodzakelijk om het toezicht onder de loep te leggen. Cultuur+Ondernemen en de Nederlandse Vereniging Toezicht Cultuur (NVTC) deden in 2015 gezamenlijk onderzoek naar ontwikkelingen op het gebied van bestuur en toezicht binnen de cultuursector. Tijdens de workshop presenteren de onderzoekers de eerste, meest opzienbarende resultaten. Maar ook toekomstige trends van het interne toezicht komen ter sprake. Daarbij is volop aandacht voor verschillen tussen regio&#8217;s. Die onderzoeksresultaten zijn spannend genoeg, maar in de workshop gaat u zelf ook bijdragen aan het onderzoek. In een rondetafelgesprek over een onderwerp dat u aanspreekt, formuleert u met elkaar drie aanbevelingen die Cultuur+Ondernemen en de NVTC kunnen meenemen in de rapportage over dit onderzoek, dat in 2016 zal verschijnen.</p>
<h4><br /> <strong>15.30 - 16.30 uur: Motorruimte</strong> <br /><strong>Cultuureducatiesysteem: lokaal en vraaggestuurd</strong>&#160;</h4>
<p><strong>Sprekers</strong><br />Moniek Warmer (Musea Utrecht), Geny Nijboer (Stadkamer), <a href="/medewerkers/theo-van-adrichem">Theo van Adrichem</a>&#160;(Cultuur+Ondernemen) &#160; &#160;&#160;</p>
<p>Scholen beheren meestal zelf het budget voor cultuureducatie. Zij kunnen in veel gemeenten en regio's zelf een keuze maken uit het aanbod van musea, podia en particuliere aanbieders. Culturele instellingen sluiten graag aan bij de vraag en de behoefte van de leerkrachten. Denk aan het aanhaken bij het curriculum en/of de leerlijnen vanuit de school. In deze workshop presenteren we drie instrumenten die vanuit de gemeente of musea ingaan op de vraag van de scholen. Moniek Warmer vertelt over het project 'Samenhang(en) in Utrecht': daar onderzoeken leerkrachten en museumeducatoren op welke manier samenhang het beste kan worden vormgegeven. Hoe kunnen de programma's aansluiten bij verschillende vragen van de basisscholen? Cultuur+Ondernemen heeft voor de gemeente Amsterdam het financi&#235;le instrument 'Voucherbeheer Amsterdam' ontwikkeld. Hiermee beheren scholen in Amsterdam zelf het gemeentelijke cultuureducatiebudget. Geny Nijboer van Stadkamer vertelt over het 'Zwolse model', waarbij de vraag van de school leidend is.&#160;<br /><br /></p>
<p>Het volledige programma vindt u op de website van <a href="http://www.cultuurinbeeld.com/programma/deelprogramma/" target="_blank">Cultuur in Beeld</a>.</p>
<p>&#160;</p><?php }} ?>
